/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reservation;

import static Reservation.LoginForm.usernameStr;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Silence
 */
public class DebtCardForm extends javax.swing.JFrame {

    /**
     * Creates new form DebtCardForm
     */
    Connection con;
    PreparedStatement pst ;
            
    public DebtCardForm() {
        con = DBConnector.ConnectDb();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        price.setText(""+BookTicketForm.totalamount);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardnameTxt = new javax.swing.JTextField();
        accountnumberTxt = new javax.swing.JTextField();
        paidBtn = new javax.swing.JButton();
        loginpageBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 55)); // NOI18N
        jLabel1.setText("Debit Card");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Card Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 150, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Account number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, 30));

        cardnameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(cardnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 170, 40));

        accountnumberTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountnumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountnumberTxtActionPerformed(evt);
            }
        });
        jPanel1.add(accountnumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 170, 40));

        paidBtn.setBackground(new java.awt.Color(245, 235, 118));
        paidBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        paidBtn.setText("Paid");
        paidBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidBtnActionPerformed(evt);
            }
        });
        jPanel1.add(paidBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 110, 35));

        loginpageBtn.setBackground(new java.awt.Color(245, 235, 118));
        loginpageBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        loginpageBtn.setText("Home");
        loginpageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpageBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginpageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 110, 35));

        exitBtn.setBackground(new java.awt.Color(245, 235, 118));
        exitBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 110, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Total Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 100, 30));

        price.setEditable(false);
        price.setBackground(new java.awt.Color(255, 255, 255));
        price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 170, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reservation/Airplane.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 748));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidBtnActionPerformed

            try{
                String sql = "Insert into transactions (username, total_amount) values(?,?)";
                pst = con.prepareStatement(sql);
//                              pst.setString(1, usernameStr);

                pst.setString(1, usernameStr);
                pst.setInt(2, Integer.parseInt(price.getText()));
                pst.execute();
                JOptionPane.showMessageDialog(null,"Payment Successfully");                
            
            }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null,"Account number invalid");                
            } catch (SQLException ex) {
            Logger.getLogger(DebtCardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_paidBtnActionPerformed

    private void cardnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnameTxtActionPerformed

    private void accountnumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountnumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountnumberTxtActionPerformed

    private void loginpageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpageBtnActionPerformed
        setVisible(false);
        new WelcomeForm().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpageBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
    }//GEN-LAST:event_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebtCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebtCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebtCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebtCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebtCardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumberTxt;
    private javax.swing.JTextField cardnameTxt;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginpageBtn;
    private javax.swing.JButton paidBtn;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
